USE Central;
DROP TABLE IF EXISTS Discovery;
CREATE TABLE Discovery
(
	Id INT(32) UNSIGNED NOT NULL AUTO_INCREMENT,
	InsertedTS TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UpdatedTS TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	
	Environment varchar(3) NOT NULL,
	ServiceName varchar(50) NOT NULL,
	Name varchar(250) NOT NULL,
	Value varchar(1000) NOT NULL,

	INDEX (Environment),
	KEY (Id)
);
ALTER TABLE Discovery ADD CONSTRAINT PK_Id PRIMARY KEY(Id);
