USE Central;
DROP TABLE IF EXISTS Hosts;
CREATE TABLE Hosts
(
	Id INT(32) UNSIGNED NOT NULL AUTO_INCREMENT,
	InsertedTS TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UpdatedTS TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

	Environment varchar(3) NOT NULL,
	Type varchar(25) NOT NULL,
	Purpose varchar(25) NOT NULL, 
	HostName varchar(255)  NOT NULL,
	Description varchar(1000)  NOT NULL,

	INDEX (Environment),
	KEY(Id)
);
ALTER TABLE Hosts ADD CONSTRAINT PK_HostName PRIMARY KEY(HostName);
