USE Backbone;
DROP TABLE IF EXISTS UserPreferences;
CREATE TABLE UserPreferences
(
	Id INT(32) UNSIGNED NOT NULL AUTO_INCREMENT,
	UserId varchar(25)  NOT NULL,
	Properties LONGTEXT   NOT NULL,
	InsertedTS TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UpdatedTS TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY(Id)
);
ALTER TABLE UserPreferences ADD CONSTRAINT PK_UserId PRIMARY KEY(UserId);
