USE Backbone;
DROP TABLE IF EXISTS MessagingAliases;
CREATE TABLE MessagingAliases
(
	Id INT(32) UNSIGNED NOT NULL AUTO_INCREMENT,
	
	Alias varchar(25)  NOT NULL,
	Topic varchar(150)  NOT NULL,
	PartitionNo INT(32) DEFAULT -1,
	
	InsertedTS TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UpdatedTS TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY(Id)
);
