USE Backbone;
DROP TABLE IF EXISTS MessagingTopics;
CREATE TABLE MessagingTopics
(
	Id INT(32) UNSIGNED NOT NULL AUTO_INCREMENT,
	
	Topic varchar(150)  NOT NULL,
	PartitionerAlgorithm varchar(50)  NOT NULL,

	InsertedTS TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UpdatedTS TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY(Id)
);
